version: "3"
services:
  frontend:
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
